CREATE DATABASE blog;

CREATE TABLE writeblog(
blog_id SERIAL PRIMARY KEY,
title VARCHAR(100) NOT NULL,
description VARCHAR(255),
CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP

)